services:
  anti:
    build: .
    image: yaroslavchybar/anti-instagram:latest
    container_name: anti-instagram
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./profiles:/app/profiles
      - ./logs:/app/logs
